name: Maven CI/CD

on:
 push

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: run server tests
      working-directory: ./JGitServer
      run: mvn test

    - name: run client tests
      working-directory: ./JGitClient
      run: mvn test

    # - name: run tests
    #   run: mvn test

    